version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: galenit-user
      POSTGRES_PASSWORD: "g@lenit"
      POSTGRES_DB: galenit-dev
    ports:
      - "15432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - galenit-network
    restart: unless-stopped
  backend:
    build: backend
    networks:
      - galenit-network
    expose:
      - 8081
    ports:
      - 8081:8080
    restart: unless-stopped
    depends_on:
      - database
  frontend:
    build: frontend
    networks:
      - galenit-network
    expose:
      - 8082
    ports: 
      - 8082:8080
    restart: unless-stopped
    depends_on:
      - backend

networks: 
  galenit-network:
    driver: bridge

volumes:
  dbdata: